import { ReactNode } from "react";
import type { Metadata } from "next";
import { Header } from "./components/layout/Header";
import '@/app/globals.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }: { children: ReactNode }) {
 return (
   <html lang="de">
     <head>
       <link rel="icon" href="/favicon.ico" />
     </head>
     <body>
       <Header />
       {/* <Navigation /> */}
       <main>{children}</main>
       {/* <Footer /> */}
     </body>
   </html>
 );
}


